name: Static Application Security Testing with SonarQube and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: Employee
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x employee/gradlew

      # - name: Start SonarQube container
      #   run: |
      #     # Start SonarQube container using Docker
      #     docker run -d -p 9000:9000 --name sonarqube sonarqube:community

      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube to start..."
          for i in {1..30}; do
            if curl -s http://localhost:9000 | grep -q "SonarQube"; then
              echo "SonarQube is up and running!"
              break
            fi
            echo "Waiting for SonarQube..."
            sleep 10
          done

      - name: Build with Gradle and Run SonarQube Test
        run: |
          cd employee
          ./gradlew clean build --warning-mode all  # Show all deprecation warnings
          ./gradlew test --tests SonarQubeIntegrationTest

          # Run the SonarQube analysis, pointing to the correct container port
          ./gradlew sonar \
            -Dsonar.login=admin \
            -Dsonar.projectKey=employee \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.token=squ_2dac043a19e8d56d448f2ad292be20f5def26311

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: employee/build/reports/sonar/report.sarif
