name: Static Application Security Testing with SonarQube and TestContainers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle and Run SonarQube Test
        run: |
          cd employee
          ./gradlew clean build
          ./gradlew test --tests SonarQubeIntegrationTest

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/sonar/report.sarif
